[project]
name = "cython-notes"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.8"
dependencies = [
    "cython>=3.1.2",
    "ipython>=8.12.3",
    "setuptools>=75.3.2",
]
